print("The Area and Perimeter program")
print()
length = int(input("Please enter the length: "))
width = int(input("Please enter the width: "))
print()
area = length * width
perimeter = 2 * (length + width)
print("Area = " + str(area))
print("Perimeter = " + str(perimeter))
print()
print("Bye!")
